### ISSUE TITLE
Icon Pack Support

### ISSUE THREAD

**Issue by JackEblan** [JackEblan/EblanLauncher#126]
Title says it all.

**Comment by JackEblan** [comment]
Can't believe this is actually just a community API hacks eh 😂 I make more research 'bout this. Even stock launchers don't support icon packs as others are tied to the launcher itself. I'll treat this as low priority for now, maybe if I release the Alpha experimental version with user feedbacks. I'll focus on something else.

TLDR: Icon packs hurt app's performance that's why google doesn't support it.

**Comment by T31n** [comment]
Icon packs initial support, the applying is slower because we have to import each application icon pack to cache. This is what I can do to optimize the performance. The algorithm might change because this is just for testing. Take note, be sure to grant the Notification permission to run the service.

![Image](https://github.com/user-attachments/assets/3bb9210e-c29f-4dc2-9a97-7460583f21ab)

![Image](https://github.com/user-attachments/assets/e89873fa-aa91-4872-899c-bcf529b81f57)

**Comment by n-o-o-b** [comment]
This doesn't work for me. Selecting Arcticons as the icon pack (having imported it using the 'Import Icon Pack' feature) just gives me a notification that says:

'**Syncing data**
This may take a while'.

The notification disappears if I go to another app and reappears if I go to the launcher again, making a notification sound again.

**Comment by T31n** [comment]
> This doesn't work for me. Selecting Arcticons as the icon pack (having imported it using the 'Import Icon Pack' feature) just gives me a notification that says:
> 
> '**Syncing data** This may take a while'.
> 
> The notification disappears if I go to another app and reappears if I go to the launcher again, making a notification sound again.

Have you selected the Icon pack after imported in **General Settings**/**Select Icon Pack**?

**Comment by n-o-o-b** [comment]
Yes. That's what caused the notification to appear.

**Comment by T31n** [comment]
> Yes. That's what caused the notification to appear.

Thanks I reproduced it. It'll be fixed on the next release.

**Comment by n-o-o-b** [comment]
Thank you. I look forward to it!

**Comment by T31n** [comment]
> Thank you. I look forward to it!

I have released a **Pre-release** that you can try earlier
https://github.com/JackEblan/EinsteinLauncher/releases/tag/v0.3.8-alpha

**Comment by n-o-o-b** [comment]
I downloaded it and installed it. Still doesn't work for me. By the way, the notification is also interrupted if I go to the launcher settings and back out again. Whenever the notification is interrupted the timer restarts from the beginning and the notification sound plays.

**Comment by n-o-o-b** [comment]
Ah. Now I deleted the icon pack from 'Select Icon Pack' in Einstein Launcher and imported it again and selected it and now it works. Thank you.

**Comment by n-o-o-b** [comment]
However, the notification is still there. And for some reason the icons look grey on the home screen when they are in folders. It's not good, it's bad for contrast. White-on-black is better than grey-on-black. Besides, you are not changing the colour of stock coloured icons. You should not change the colour of these either.

**Comment by n-o-o-b** [comment]
I've just turned my brightness up and now I don't know, maybe it's just because they are so small it seems that way, and the colour has not been changed. In general, I don't know why your icons and labels are so small by default. It's not good, will probably lead to eye strain in the long run. I don't know why you don't use an average sort of size like on most stock launchers.

**Comment by T31n** [comment]
Can you provide the screenshot?

**Comment by n-o-o-b** [comment]
Here you go.

<img width="1080" height="2160" alt="Image" src="https://github.com/user-attachments/assets/8604b6e6-5d6b-4d15-817c-981cfda89963" />

<img width="1080" height="2160" alt="Image" src="https://github.com/user-attachments/assets/fd415e39-0908-4853-b1c7-ecfbdc290857" />

**Comment by T31n** [comment]
1. You can block the notifications on your device and we discussed it here #425 
2. You can change the size of the app icon and label in the **Settings/Home/GridItem**

**Comment by n-o-o-b** [comment]
I shouldn't need to block notifications! (I think I will just keep an eye on the issue tracker and wait till the issue is solved before trying to use Einstein as a daily driver.)

I can change the icon and label sizes in the settings but I was just saying the default isn't good.

Also, now some of the icons have changed. Compare with Lawnchair. (Einstein 1st, Lawnchair 2nd.)

![Image](https://github.com/user-attachments/assets/9017c110-fb51-4d49-912b-cf447ab2c382)
![Image](https://github.com/user-attachments/assets/2abc4cc3-53d1-4605-972e-d4f1f5565db8)
![Image](https://github.com/user-attachments/assets/1a8214d2-5ac8-42f5-9239-b72a6effafa5)
![Image](https://github.com/user-attachments/assets/3db771fa-a9d8-4d92-9b80-0ac5d682fc28)

**Comment by n-o-o-b** [comment]
Another couple of examples.

![Image](https://github.com/user-attachments/assets/63d5e364-9866-49ef-bb8e-3f0b1788365f)
![Image](https://github.com/user-attachments/assets/67923b93-97c6-4595-a280-00c4d6fdf30b)
![Image](https://github.com/user-attachments/assets/76f9dfbe-027a-4316-a679-8d53ce50c5d1)
![Image](https://github.com/user-attachments/assets/8d097cfc-f84e-4868-9ae6-f802db4132f5)

**Comment by n-o-o-b** [comment]
Regarding the icons, I have noticed this has also happened in another launcher. One icon (the Gallery icon) is also incorrect for me in [Kvaesitso](https://kvaesitso.mm20.de/).

Because of this, I suspect that this might be an app icon pack issue rather than a launcher issue, although I'm not 100% sure.

I have filed a bug report here: https://github.com/Arcticons-Team/Arcticons/issues/3212.

**Comment by n-o-o-b** [comment]
This might help you, if you haven't seen it already: https://github.com/Arcticons-Team/Arcticons/issues/3212#issuecomment-3779109549.
